package ahnsortingefficiencies;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.awt.Color;

/* Jay Ahn
 * Nov 25 2025
 * Program that compares bubble sort, quick sort, and insertion sort
 */
public class AhnSortingEfficiencies extends javax.swing.JFrame {

    //declaring two global array that contains numbers from the file and global counter for quick sort
    static int[] num10 = new int[10];//array with 10 numbers
    static int[] num10000 = new int[10000];//array with 10000 numbesr
    static int quickCount = 0;

    /**
     * Creates new form AhnSortingEfficiencies
     */
    public AhnSortingEfficiencies() {
        initComponents();
        getContentPane().setBackground(Color.CYAN);//setting the background color to cyan
        try {//attemping to open the file
            File f = new File("src/ahnsortingefficiencies/10nums.txt");//setting file f to 10nums.txt
            File f2 = new File("src/ahnsortingefficiencies/10000nums.txt");//setting file f2 to 10000nums.txt
            Scanner s = new Scanner(f);//setting scanner s to read file f
            Scanner s2 = new Scanner(f2);//setting scanner s2 to read file f2
            for (int i = 0; i < 10000; i++) {//for loop to repeat 10000 times
                if (i < 10) {//while i is less than 10
                    num10[i] = Integer.parseInt(s.nextLine());//fills num10 array with 10nums.txt
                }
                num10000[i] = Integer.parseInt(s2.nextLine());//fills num10000 array with 10000nums.txt
            }
        } catch (FileNotFoundException e) {//catching any errors that may occur
            System.out.println("Error: " + e);//displaying error message
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngNums = new javax.swing.ButtonGroup();
        btngOrder = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblnum = new javax.swing.JLabel();
        lblSort = new javax.swing.JLabel();
        lblOrder = new javax.swing.JLabel();
        rbtn10 = new javax.swing.JRadioButton();
        rbtn10000 = new javax.swing.JRadioButton();
        cbxSort = new javax.swing.JComboBox<>();
        rbtnAscending = new javax.swing.JRadioButton();
        rbtnDescending = new javax.swing.JRadioButton();
        btnSort = new javax.swing.JButton();
        lblOrginalNum = new javax.swing.JLabel();
        lblSortNums = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOriginalNums = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSortNums = new javax.swing.JTextArea();
        lblSortResult = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSortResult = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Sorting Efficiencies");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 23, -1, -1));

        lblnum.setText("Amount of numbers to sort:");
        getContentPane().add(lblnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 83, -1, -1));

        lblSort.setText("Display numbers sorted by:");
        getContentPane().add(lblSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblOrder.setText("Sort Order:");
        getContentPane().add(lblOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btngNums.add(rbtn10);
        rbtn10.setSelected(true);
        rbtn10.setText("10");
        rbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn10ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        btngNums.add(rbtn10000);
        rbtn10000.setText("10000");
        getContentPane().add(rbtn10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        cbxSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bubble Sort", "Quick Sort", "Insertion Sort" }));
        getContentPane().add(cbxSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 140, -1));

        btngOrder.add(rbtnAscending);
        rbtnAscending.setSelected(true);
        rbtnAscending.setText("Ascending");
        getContentPane().add(rbtnAscending, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        btngOrder.add(rbtnDescending);
        rbtnDescending.setText("Descending");
        getContentPane().add(rbtnDescending, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });
        getContentPane().add(btnSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 178, 200, 60));

        lblOrginalNum.setText("Original Numbers:");
        getContentPane().add(lblOrginalNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        lblSortNums.setText("Sorted Numbers:");
        getContentPane().add(lblSortNums, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        txtOriginalNums.setColumns(20);
        txtOriginalNums.setRows(5);
        jScrollPane1.setViewportView(txtOriginalNums);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 310));

        txtSortNums.setColumns(20);
        txtSortNums.setRows(5);
        jScrollPane2.setViewportView(txtSortNums);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 250, 310));

        lblSortResult.setText("Sort Results:");
        getContentPane().add(lblSortResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        txtSortResult.setColumns(20);
        txtSortResult.setRows(5);
        jScrollPane3.setViewportView(txtSortResult);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 133, 370, 480));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, -1, -1));

        jLabel8.setText(".");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, 50, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn10ActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        int[] bubble, insertion, quick;
        int bubbleC, insertionC;
        String original = "", sorted = "";
        if (rbtn10.isSelected()) {
            bubble = num10.clone();
            insertion = num10.clone();
            quick = num10.clone();
        } else {
            System.out.println("Hi");
            bubble = num10000.clone();
            insertion = num10000.clone();
            quick = num10000.clone();
        }
        for (int i = 0; i < bubble.length; i++) {
            original += i + ": " + bubble[i] + "\n";
        }
        txtOriginalNums.setText(original);
        if (rbtnAscending.isSelected()) {
            bubbleC = bubbleSortA(bubble);
            insertionC = insertionSortA(insertion);
            quickSortA(quick, 0, quick.length - 1);
        } else {
            bubbleC = bubbleSortD(bubble);
            insertionC = insertionSortD(insertion);
            quickSortD(quick, 0, quick.length - 1);
            System.out.println("HI");
        }
        if (cbxSort.getSelectedIndex() == 0) {
            for (int i = 0; i < bubble.length; i++) {
                sorted += i + ": " + bubble[i] + "\n";
            }
        } else if (cbxSort.getSelectedIndex() == 1) {
            for (int i = 0; i < quick.length; i++) {
                sorted += i + ": " + quick[i] + "\n";
            }
        } else {
            for (int i = 0; i < insertion.length; i++) {
                sorted += i + ": " + insertion[i] + "\n";
            }
        }
        txtSortNums.setText(sorted);

    }//GEN-LAST:event_btnSortActionPerformed

    /**
     * bubble sorting method for ascending order
     *
     * @param a - array of numbers
     * @return - counter for how many times a loop was executed
     */
    public static int bubbleSortA(int[] a) {
        int counter = 0;//declaring counter to track how many times a loop executes
        int k = 0;//declaring k value which will track how many elements are sorted
        boolean exchangeMade = true;//declaring boolean exchangeMade to determine if there was any exchange within array
        while (k < a.length - 1 && exchangeMade) {//while k is less than the array length - 1 and exchangeMade is true
            exchangeMade = false;//sets exchangeMade to false
            k++;//add 1 to k
            for (int i = 0; i < a.length - k; i++) {//for loop 0 to array length - k since we already sorted k amount of elements
                counter++;//adds 1 to the counter to track loop
                if (a[i] > a[i + 1]) {//if ith element is greater than i + 1th element
                    //swaping i + 1th element and ith element
                    int temp = a[i + 1];//put i + 1th element into a temporary place holder
                    a[i + 1] = a[i];//set i + 1th element to ith element
                    a[i] = temp;//set ith element to the temporary place holder from i + 1th element
                    exchangeMade = true;//set exchangemade to true;
                }
            }
        }
        return counter;//returning counter that tracked loops
    }

    /**
     * bubble sorting method for descending order
     *
     * @param a - array of numbers
     * @return - counter for how many times a loop was executed
     */
    public static int bubbleSortD(int[] a) {
        int counter = 0;//declaring counter to track how many times a loop executes
        int k = 0;//declaring k value which will track how many elements are sorted
        boolean exchangeMade = true;//declaring boolean exchangeMade to determine if there was any exchange within array
        while (k < a.length - 1 && exchangeMade) {//while k is less than the array length - 1 and exchangeMade is true
            exchangeMade = false;//sets exchangeMade to false
            k++;//add 1 to k
            for (int i = 0; i < a.length - k; i++) {//for loop 0 to array length - k since we already sorted k amount of elements
                counter++;//adds 1 to the counter to track loop
                if (a[i] < a[i + 1]) {//if ith element is less than i + 1th element
                    //swaping i + 1th element and ith element
                    int temp = a[i + 1];//put i + 1th element into a temporary place holder
                    a[i + 1] = a[i];//set i + 1th element to ith element
                    a[i] = temp;//set ith element to the temporary place holder from i + 1th element
                    exchangeMade = true;//set exchangemade to true;
                }
            }
        }
        return counter;//returning counter that tracked loops
    }

    /**
     * insertion sorting method for ascending order
     *
     * @param a - array of numbers
     * @return - counter for how many times a loop was executed
     */
    public static int insertionSortA(int[] a) {
        int counter = 0;//declaring counter that will track the number of loops executed
        int key;//unsorted element that is being sorted
        int j;//index of sorted item that is being compared to key which is unsorted element
        for (int i = 1; i < a.length; i++) {//for loop 1 to length of the array. Starts at 1 because insertion sorting method consider the first element already sorted
            key = a[i];//setting key to ith element
            j = i - 1;//setting j to i - 1 because element before i is already considered sorted
            while (j >= 0 && a[j] > key) {//while j is geater or equal to 0 and jth element is greater than key (unsorted item is less than sorted ones on the left)
                //unsorted item moves down until it is sorted on the right index
                a[j + 1] = a[j];//set j + 1th(key) element to jth element
                j--;//subtract 1 from j
                counter++;//add 1 to the counter to track loop
            }
            a[j + 1] = key;//set j + 1th element to key
        }
        return counter;//return counter that tracked loops
    }

    /**
     * insertion sorting method for descending order
     *
     * @param a - array of numbers
     * @return - counter for how many times a loop was executed
     */
    public static int insertionSortD(int[] a) {
        int counter = 0;//declaring counter that will track the number of loops executed
        int key;//unsorted element that is being sorted
        int j;//index of sorted item that is being compared to key which is unsorted element
        for (int i = 1; i < a.length; i++) {//for loop 1 to length of the array. Starts at 1 because insertion sorting method consider the first element already sorted
            key = a[i];//setting key to ith element
            j = i - 1;//setting j to i - 1 because element before i is already considered sorted
            while (j >= 0 && a[j] < key) {//while j is less or equal to 0 and jth element is less than key (unsorted item is greater than sorted ones on the left)
                //unsorted item moves down until it is sorted on the right index
                a[j + 1] = a[j];//set j + 1th(key) element to jth element
                j--;//subtract 1 from j
                counter++;//add 1 to the counter to track loop
            }
            a[j + 1] = key;//set j + 1th element to key
        }
        return counter;//return counter that tracked loops
    }

    /**
     * quick sorting method for ascending order
     *
     * @param a - array of numbers
     * @param left - left most index of the array
     * @param right - right most index of the array
     */
    public static void quickSortA(int[] a, int left, int right) {
        if (left >= right) {
            return;
        }
        int i = left, j = right;
        int pivot = a[(left + right) / 2];
        while (i < j) {
            while (a[i] < pivot) {
                i++;
            }
            while (a[j] > pivot) {
                j--;
            }
            if (i <= j) {
                int temp = a[i];
                a[i] = a[j];
                a[j] = temp;
                i++;
                j--;
                quickCount++;
            }
            quickSortA(a, left, j);
            quickSortA(a, i, right);
        }
    }

    /**
     * quick sorting method for descending order
     *
     * @param a - array of numbers
     * @param left - left most index of the array
     * @param right - right most index of the array
     */
    public static void quickSortD(int[] a, int left, int right) {
        if (left >= right) {
            return;
        }
        int i = left, j = right;
        int pivot = a[(left + right) / 2];
        while (i < j) {
            while (a[i] > pivot) {
                i++;
            }
            while (a[j] < pivot) {
                j--;
            }
            if (i <= j) {
                int temp = a[i];
                a[i] = a[j];
                a[j] = temp;
                i++;
                j--;
                quickCount++;
            }
            quickSortD(a, left, j);
            quickSortD(a, i, right);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AhnSortingEfficiencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AhnSortingEfficiencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AhnSortingEfficiencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AhnSortingEfficiencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AhnSortingEfficiencies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSort;
    private javax.swing.ButtonGroup btngNums;
    private javax.swing.ButtonGroup btngOrder;
    private javax.swing.JComboBox<String> cbxSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrginalNum;
    private javax.swing.JLabel lblSort;
    private javax.swing.JLabel lblSortNums;
    private javax.swing.JLabel lblSortResult;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblnum;
    private javax.swing.JRadioButton rbtn10;
    private javax.swing.JRadioButton rbtn10000;
    private javax.swing.JRadioButton rbtnAscending;
    private javax.swing.JRadioButton rbtnDescending;
    private javax.swing.JTextArea txtOriginalNums;
    private javax.swing.JTextArea txtSortNums;
    private javax.swing.JTextArea txtSortResult;
    // End of variables declaration//GEN-END:variables
}
